_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "weights/tt_res50_finetune_synth-tt-mlt-13-15-textocr.pth"

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("inversetext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)  # no step
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/inversetext_eval"