_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "weights/R-50.pkl"
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl" 

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test", "inversetext_test",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (120000,)  # no step
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 20000

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/3090_totaltext_pretrain"