_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "weights/res50_pretrain_synth-tt-mlt-13-15-textocr.pth"

DATASETS:
  TRAIN: ("totaltext_train_148voc","mlt_148voc","ic13_train_148voc","ic15_train_148voc", "textocr1_148voc", "textocr2_148voc","rumsey_train_148voc",)
 
  # TRAIN: ("rumsey_train_148voc",)
  TEST: ("rumsey_val_148voc",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (30000,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 4000

TEST:
  EVAL_PERIOD: 2000
  LEXICON_TYPE: None

OUTPUT_DIR:  "output/R_50/pretrain/pretrain_rumsey_bs4_frozen"